version: '3'

services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres_db'
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=appointment'
    ports:
      - '5432:5432'

