app:
  service:
    shortest:  30
    interval: 30
server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: changeme
    password: changeme
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  quartz:
    jdbc:
      initialize-schema:
        always
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          threadPool:
            threadNamePrefix: quartz-worker
            threadCount: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
          jobStore:
            isClustered: true
            clusterCheckinInterval: 5000
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate

logging:
  level:
    com.aleksmurmur.*: DEBUG
  file:
    name: app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB